import { GeocodeResult } from './types';

export const ADDRESS_FALLBACKS: Array<{ needles: string[]; result: GeocodeResult }> = [
  {
    needles: ['puławska 1', 'pulawska 1', 'warszawa'],
    result: {
      label: 'ul. Puławska 1, Mokotów, Warszawa, mazowieckie, Polska',
      lat: '52.1818',
      lon: '21.0227',
      city: 'Warszawa',
      suburb: 'Mokotów',
      road: 'Puławska',
      houseNumber: '1',
      postcode: '02-515',
      county: 'Warszawa',
      state: 'mazowieckie',
      municipality: 'Warszawa',
      keyCity: 'warszawa',
      keySuburb: 'mokotow',
      keyMunicipality: 'warszawa',
    },
  },
  {
    needles: ['paszowice'],
    result: {
      label: 'Paszowice, jaworski, dolnośląskie, Polska',
      lat: '51.0100',
      lon: '16.1500',
      city: 'Paszowice',
      suburb: 'Paszowice',
      road: '',
      houseNumber: '',
      postcode: '59-411',
      county: 'jaworski',
      state: 'dolnośląskie',
      municipality: 'Paszowice',
      keyCity: 'paszowice',
      keySuburb: 'paszowice',
      keyMunicipality: 'paszowice',
    },
  },
  {
    needles: ['kobyłka', 'kobylka'],
    result: {
      label: 'Kobyłka, wołomiński, mazowieckie, Polska',
      lat: '52.3390',
      lon: '21.1950',
      city: 'Kobyłka',
      suburb: 'Kobyłka',
      road: '',
      houseNumber: '',
      postcode: '05-230',
      county: 'wołomiński',
      state: 'mazowieckie',
      municipality: 'Kobyłka',
      keyCity: 'kobylka',
      keySuburb: 'kobylka',
      keyMunicipality: 'kobylka',
    },
  },
];
